<!DOCTYPE html>

<html lang="es">

<head>

    <meta charset="UTF-8">

    <title>Películas</title>

    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
    >

    <link rel="stylesheet" href="css/style.css">

</head>

<body>

<nav class="navbar navbar-dark bg-dark">

    <div class="container">

        <a
            class="navbar-brand"
            href="peliculas"
        >
            Películas
        </a>

    </div>

</nav>