<div class="card">

    <div class="card-body">

        <form method="POST" action="addDirector">

            <input
                required
                name="nombre"
                type="text"
                class="form-control mb-2"
                placeholder="Nombre"
            >

            <input
                required
                name="fecha_nacimiento"
                type="date"
                class="form-control mb-2"
            >

            <input
                required
                name="edad"
                type="number"
                class="form-control mb-2"
                placeholder="Edad"
            >

            <button
                type="submit"
                class="btn btn-primary"
            >
                Agregar director
            </button>

        </form>

    </div>

</div>