<?php require __DIR__ . '/layout/header.phtml' ?>

<main class="container mt-4">

    <div class="row">

        <aside class="col-lg-4">

            <?php require __DIR__ . '/director-form.phtml' ?>

        </aside>

        <section class="col-lg-8">

            <?php require __DIR__ . '/directores-list.phtml' ?>

        </section>

    </div>

</main>

<?php require __DIR__ . '/layout/footer.phtml' ?>