<?php require __DIR__ . '/layout/header.phtml' ?>

<main class="container mt-4">

    <div class="card">

        <div class="card-body">

            <h1><?= $pelicula->nombre ?></h1>

            <p>

                Fecha estreno:

                <?= $pelicula->fecha_estreno ?>

            </p>

            <p>

                Nacionalidad:

                <?= $pelicula->nacionalidad ?>

            </p>

            <p>

                Director:

                <?= $pelicula->director ?>

            </p>

        </div>

    </div>

</main>

<?php require __DIR__ . '/layout/footer.phtml' ?>