<?php require __DIR__ . '/layout/header.phtml' ?>

<main class="container mt-4">

    <div class="row">

        <aside class="col-lg-4 mb-3">

            <?php require __DIR__ . '/pelicula-form.phtml' ?>

        </aside>

        <section class="col-lg-8 mb-3">

            <?php require __DIR__ . '/peliculas-list.phtml' ?>

        </section>

    </div>

</main>

<?php require __DIR__ . '/layout/footer.phtml' ?>